### PR TITLE
Update deps for Sailfish OS 2.0.5

### PR DESCRIPTION
**Pull request by ilpianista**
`qt5-plugin-geoservices-nokia` has been renamed as `qt5-plugin-geoservices-here`.

### CODE REVIEW

**Comment by otsaloma** [comment]
I haven't installed 2.0.5 yet, so I can't test. Did you test that your fix works? Is it really just the package name changed, not the API -- e.g. the [plugin name](https://github.com/otsaloma/poor-maps/blob/master/qml/MapPlugin.qml#L36)?

**Comment by ilpianista** [comment]
Nope, I didn't test it. I thought it was only the package name that is changed.

I'll try test it this evening.

**Comment by otsaloma** [comment]
It's hard to tell from the version number, but it's likely that they have backported the API changes of the HERE plugin, which would mean the name "here" and "here." prefixes on the parameter names.

http://doc.qt.io/qt-5/location-plugin-here.html#parameters

I'll probably upgrade and test on the weekend.

**Comment by otsaloma** [comment]
There was a small API change: `app_code` instead of `token`. With that change it works. Merging.

**Pull request merged**
