### PR TITLE
adding support for OSM Scout Server router

### PR DESCRIPTION
**Pull request by rinigus**
This PR adds support for routing using OSM Scout Server. I formatted the routing results following mapzen as an example (not 100% compatible due to slightly different formatting and availability of information). I am preparing for the next release of the server that has support for routing. Not 100% sure about timing, but I plan to release it in few days.

There are issues regarding timeouts (as we discuss under https://github.com/otsaloma/poor-maps/issues/23 ), but this is not related to this PR, I think.

### CODE REVIEW

**Comment by otsaloma** [comment]
Looks all right to me in general. I'll do some minor tweaks and I think I'll add some kind of a subtitle field to `BusyIndicator` so that we could add below the spinner and "Searching" text something like "This could take up to a minute for long routes." in smaller font and secondary color.

You kept some of the maneuver icons copied from Mapzen as commented out. Do you plan update the list or is the current ones what you get from libosmscout? If it's all you get, please remove the rest instead of commenting them out.

I'll test again before merging. I'm working on fixing a minor rotation issue (#13), which requires some field-testing before a release, so I have chosen to delay the 0.26 release till maybe next weekend, which means I should get routing in that too.

**Comment by rinigus** [comment]
I have removed the commented out code. The implemented icons are all what I have at present. It was mainly kept for a reference to see what's missing in libosmscout (absence of u-turn, for example). I can keep this reference somewhere else, it doesn't have to be installed on all devices - that's true.

As for indicator with the help message, that's a great idea. It would be of help for local server calculations.

**Comment by otsaloma** [comment]
I have some changes, but I didn't manage to push them to your branch. Is the "Allow edits from maintainers" off or do I have some problems of my own?

https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by rinigus** [comment]
Morning:

"Allow edits from maintainers" is on...

**Comment by rinigus** [comment]
Just to clarify - it was on from the beginning. Maybe its some other problem...

**Comment by otsaloma** [comment]
OK, I just had the remote origin in `.git/config` set wrong. Worked fine to pull, but not push.

Couple notes about the changes:
- I removed radius from the query. It was at the same value as the server default, so there's no change, but I think it's better that you can change the default at the server side and it will affect Poor Maps as well. Right?
- I removed the verbal pre and post instructions as they are not used anywhere. It will save a kilobyte or two of memory and a couple milliseconds of processing time. If it's specifically verbal instructions, we can return to that when Poor Maps has some kind of a speech system. That is nowhere in sight.
- The instruction texts seem to use single quotes around all names. I'd suggest dropping those, or if it's from libosmscout, telling them to drop them. I find them unnecessary, verbose and distracting.

I didn't yet actually run the router, but will do so on saturday or sunday and can merge after that.

**Comment by rinigus** [comment]
I managed to run it for few queries, it seems to be all fine. The only thing I didn't notice in practice - the note regarding that the route calculation can take long was not displayed on the phone (I saw your change in QML, haven't checked it though). 

Re radius: Sure, we can expose it in the server as well. I haven't done it so far, but its possible - no problem. And it will be then the same for all clients.

Re post/pre: I thought that these could be displayed before or after the corresponding action (like 200 meters in advance for pre?). Very close to action, it maybe possible to display the currently displayed text. But, its possible to test it later ...

Re quotes: these originate from the demo in libosmscout and I used the same notation in the server as well. This can be easily fixed in my code (will make an issue).

While testing the routing, I encountered one place in Tallinn where it was suggesting to take an illegal left turn. This turned out to be a bug in the importer of the libosmscout (the issue will be hopefully fixed soon). But otherwise it was all fine for me.

However, with the local router, it would be great to have an ability in Poor Maps to automatically recalculate the route if the driver takes other course. There should be ways to optimize it (like using earlier route as a reference by adding more points into the query), but such functionality would be great. I understand that when we use a remote service its rather expensive (shared resource), but, for the local one, the recalculation should be fine.

**Comment by otsaloma** [comment]
> The only thing I didn't notice in practice - the note regarding that the route calculation can take long was not displayed on the phone (I saw your change in QML, haven't checked it though).

OK, I'll check that when I test.

> Re radius: Sure, we can expose it in the server as well. I haven't done it so far, but its possible - no problem. And it will be then the same for all clients.

I read in your README that the readius is "distance from the points in meters where closest routing point is searched for (1000 meters by default)". Did I misunderstand? Either way, it sounds like an implementation detail that you know better yourself and cannot expect clients to understand or maintain hard-coded values of.

> Re post/pre: I thought that these could be displayed before or after the corresponding action (like 200 meters in advance for pre?)

You can add an issue for that, but I'm hesitant about it. If it was really verbal, more information would be OK, but if it needs to be read from screen, then the amount of text and amount of changes is best kept to a minimum.

> However, with the local router, it would be great to have an ability in Poor Maps to automatically recalculate the route if the driver takes other course.

Yes, this would be nice to have, I think for online routers too. You can add an issue for that too.

**Comment by rinigus** [comment]
I filed the issue regarding route auto-correction. 

Re verbal instructions: you are right, reading from screen may end up being just a distraction. Let's wait for voice synthesis to get it working. I'll keep them in the reply, as Mapzen has, so it would be easy to test it later.

Re radius: yes, you understand correctly. Let's drop it in client for now. In general, I think there is similar parameter in all routers, but 1km default should be OK for now.

**Comment by otsaloma** [comment]
I tried the router. My observations:
1. The `BusyModal` message works fine for me.
2. When using coordinates, the server often returns `500: 'unknown command'`. Some coordinates seem to work, others don't. You can test this in Poor Maps by long-tapping to add a point and then trying to navigate to that point.
3. At one point the server started returning `BadStatusLine: ''` and `ConnectionRefusedError: [Errno 111] Connection refused`. As far as I can tell, it crashed, but I don't have any steps to reproduce that.
4. Some routes seem to have the final maneuver point that marks the arrival in the wrong place. This confuses the algorithm that figures out which instruction to show by comparing the position and the route polyline. The exact final route point should also be the point of the arrival maneuver point.
   - See e.g. `http://localhost:8553/v1/route?type=car&p[0][search]=Helsinki&p[1][lng]=24.924865&p[1][lat]=60.178061` for a query where it's wrong. I have used [Mapzen's Metro extract of Helsinki](https://mapzen.com/data/metro-extracts/metro/helsinki_finland/) when testing.
   - See the [HSL router](https://github.com/otsaloma/poor-maps/blob/master/routers/hsl.py#L156) for how to set it, if it needs to be corrected in the provider code instead of the server.

Of the above, 2 and 3, are no problems for merging. We can get this out for testers, they can file bug reports and you can fix them on the server side. Number 4 I'd like to see fixed before merging.

**Comment by rinigus** [comment]
My bad - I had Poor Maps modules for routing under .local/share/harbour-poor-maps. So, I was testing my own older code, sorry for that. 
1. BusyModal works for me too.
2. Strangely, I don't get any errors when I select coordinate in Poor Maps by long-tapping. I have found one address in Tallinn where there is an issue with finding route to it, but coordinates worked for me so far. Where do you see the return values and 'unknown command' in Poor Maps? Would you mind to look into the servers events log when you get this reply? I'll have to make the error messages more clear, that would hopefully help debugging the issue. Maybe you could give me an example URL that was get such reply?
3. Connection refused could happen if all threads are busy (that's what should be resolved by new HTTP engine). I still haven't implemented the CPU count detection as we discussed earlier (its under issues in the server github) and its possible that the number of active threads is lower on your device. You could check an ini file at .config/harbour-osmscout-server/ to see number of maximal allowed connections. Maybe it has to be increased.
4. I think I know what you mean, I missed this, sorry. I'll prefer to fix it on the server side - we don't need to introduce some workarounds if it can be fixed at the source. I'll look into it as soon as I can. I'll try to fix this bug as my next task with the http engine rewrite postponed until this is resolved.

Thank you very much for testing the router and these thorough comments!

**Comment by rinigus** [comment]
I have just fixed [4] in the latest commits. It seems that there is an issue in the library and I would have to dig a bit later for proper fix. Right now, in case if the last instruction was arrival (which it should be), I alter the coordinates to correspond to the last route point. For me, it seems that the target point before was one point before last in the proposed route. 

With this temporary fix, routing seem to be working and Poor Maps displays the last point as a target, as it is supposed to be. I'll release new RPMs later today via OpenRepos.

**Comment by rinigus** [comment]
Just to let you know - new RPMs are out and bug [4] should be fixed now.

**Comment by otsaloma** [comment]
Arrival point looks fine now. Thanks, merging. I'll file issues against your server for the unknown command and crash. And I'll make a release within the next couple days.

**Pull request merged**
